# Generated by Django 4.2.1 on 2023-05-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='educationqualifications',
            unique_together=set(),
        ),
    ]
