# Generated by Django 4.2.1 on 2023-06-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsform',
            name='blood_group',
            field=models.IntegerField(choices=[(5, 'AB+'), (2, 'A-'), (6, 'AB-'), (7, 'O+'), (9, 'थाछैन'), (1, 'A+'), (8, 'O-'), (3, 'B+'), (4, 'B-')]),
        ),
    ]
