# Generated by Django 4.2.1 on 2023-06-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_personsform_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsform',
            name='blood_group',
            field=models.IntegerField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'AB+'), (6, 'AB-'), (7, 'O+'), (8, 'O-'), (9, 'थाछैन')]),
        ),
    ]
