# Generated by Django 4.2.1 on 2023-05-13 11:41

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_educationqualifications_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personsform',
            old_name='woda',
            new_name='permanent_address',
        ),
        migrations.AddField(
            model_name='personsform',
            name='submitter_name',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='personsform',
            name='temporary_address',
            field=models.CharField(default=builtins.print, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personsform',
            name='citizenship',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
