# Generated by Django 4.2.1 on 2023-05-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_personsform_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsform',
            name='blood_group',
            field=models.IntegerField(choices=[(4, 'B-'), (3, 'B+'), (8, 'O-'), (1, 'A+'), (9, 'थाछैन'), (5, 'AB+'), (7, 'O+'), (2, 'A-'), (6, 'AB-')]),
        ),
    ]
