# Generated by Django 4.2.1 on 2023-05-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_personsform_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsform',
            name='blood_group',
            field=models.IntegerField(choices=[(6, 'AB-'), (7, 'O+'), (2, 'A-'), (3, 'B+'), (9, 'थाछैन'), (8, 'O-'), (4, 'B-'), (5, 'AB+'), (1, 'A+')]),
        ),
    ]
