# Generated by Django 4.2.1 on 2023-05-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_rename_woda_personsform_permanent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
