# Generated by Django 4.2.1 on 2023-05-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_personsform_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsform',
            name='blood_group',
            field=models.IntegerField(choices=[(8, 'O-'), (3, 'B+'), (6, 'AB-'), (5, 'AB+'), (9, 'थाछैन'), (1, 'A+'), (7, 'O+'), (2, 'A-'), (4, 'B-')]),
        ),
    ]
