# Generated by Django 4.2.1 on 2023-06-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_personsform_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsform',
            name='blood_group',
            field=models.IntegerField(choices=[(1, 'A+'), (8, 'O-'), (3, 'B+'), (2, 'A-'), (9, 'थाछैन'), (6, 'AB-'), (5, 'AB+'), (4, 'B-'), (7, 'O+')]),
        ),
    ]
