# Generated by Django 4.2.1 on 2023-06-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_personsform_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsform',
            name='blood_group',
            field=models.IntegerField(choices=[(3, 'B+'), (9, 'थाछैन'), (5, 'AB+'), (8, 'O-'), (2, 'A-'), (4, 'B-'), (6, 'AB-'), (7, 'O+'), (1, 'A+')]),
        ),
    ]
