# Generated by Django 4.2.1 on 2023-06-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_personsform_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsform',
            name='blood_group',
            field=models.IntegerField(choices=[(1, 'A+'), (3, 'B+'), (8, 'O-'), (5, 'AB+'), (6, 'AB-'), (4, 'B-'), (9, 'थाछैन'), (2, 'A-'), (7, 'O+')]),
        ),
    ]
