# Generated by Django 4.2.1 on 2023-06-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_personsform_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsform',
            name='blood_group',
            field=models.IntegerField(choices=[(4, 'B-'), (2, 'A-'), (5, 'AB+'), (6, 'AB-'), (9, 'थाछैन'), (1, 'A+'), (3, 'B+'), (7, 'O+'), (8, 'O-')]),
        ),
    ]
