# Generated by Django 4.2.1 on 2023-05-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(blank=True, max_length=122, null=True)),
                ('mobile_number', models.PositiveIntegerField()),
                ('position', models.CharField(max_length=100)),
                ('address', models.IntegerField(choices=[(1, 'धुलिखेल वडा नं १'), (2, 'धुलिखेल वडा नं २'), (3, 'धुलिखेल वडा नं ३'), (4, 'धुलिखेल वडा नं ४'), (5, 'धुलिखेल वडा नं ५'), (6, 'धुलिखेल वडा नं ६'), (7, 'धुलिखेल वडा नं ७'), (8, 'धुलिखेल वडा नं ८'), (9, 'धुलिखेल वडा नं ९'), (10, 'धुलिखेल वडा नं १०'), (11, 'धुलिखेल वडा नं ११'), (12, 'धुलिखेल वडा नं १२')])),
            ],
        ),
    ]
