# Generated by Django 4.2.1 on 2023-05-29 18:47

import about.models
from django.db import migrations, models
import forms.storage


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=forms.storage.OverwriteStorage(), upload_to=about.models.save_user_photo),
        ),
    ]
