# Generated by Django 4.2.1 on 2023-06-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_address_alter_about_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
